// _import.cr — imports applied to all .cr files in src/compiler/
// Backend files in subdirectories use :: as path separator.
// Legacy ASM backend removed — ELF pipeline is the only path.
import cli
import ast
import globals
import dyn_arr
import lexer
import parser
import checker
import type_terms
import type_engine
import ty_shadow
import type_selftest
import diag
import ir_gen
import dataflow
import ccr_io
import ent_kernel
import module
import toml
import project
import os
import fmt
import io
import interp
import dump
import monomorph
import cir_cache
import ext_mgr
import ext_safety
import pass
import opt
import ptr_analysis
import region_check
import provenance_verify
import rt
import main
import entry
