name: CI-min
on:
  pull_request:
    branches: ["**"]
permissions:
  contents: read
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    if: github.event_name == 'pull_request'
    env:
      CI_JOB_NAME: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: check
          - name: bootstrap-tests
          - name: selfhost-tests
    steps:
      - name: checkout the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

